# Generated by Django 2.2.5 on 2019-12-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(max_length=264)),
                ('description', models.CharField(max_length=264)),
                ('amount', models.PositiveIntegerField()),
            ],
        ),
    ]
